Repository krbz999/babonus, pull requests merged in 2023-03, with the labels that each got.

#152 Translations update from Foundry Hub - Weblate
  lang/fr.json
Labels: Localization

#159 Translations update from Foundry Hub - Weblate
  lang/fr.json
Labels: Localization

#162 Implement Ability Check Babonus type
  README.md
  lang/en.json
  scripts/applications/babonus.mjs
  scripts/applications/bonusCollector.mjs
  scripts/applications/dataModel.mjs
  scripts/constants.mjs
  scripts/filters.mjs
  scripts/helpers/helpers.mjs
  scripts/hooks.mjs
  setup.mjs
Labels: Enhancement, Feature Request

#163 Implement hit points as a consumable resource
  README.md
  lang/en.json
  scripts/applications/auraConfigurationApp.mjs
  scripts/applications/consumptionApp.mjs
  scripts/applications/dataModel.mjs
  scripts/applications/rollConfigApp.mjs
  scripts/filters.mjs
  templates/subapplications/consumptionApp.hbs
Labels: Enhancement, Feature Request

#170 Fix missing label in Keys dialog
  templates/subapplications/keysDialog.hbs
Labels: Bug, UI

#171 Add anchors in Applied Bonuses dialog
  templates/subapplications/appliedBonusesDialog.hbs
Labels: Enhancement, UI

#175 Merge needed and unfit and implement to object
  README.md
  lang/en.json
  scripts/applications/babonus.mjs
  scripts/applications/dataFields.mjs
  scripts/applications/dataModel.mjs
  scripts/applications/keysDialog.mjs
  scripts/filters.mjs
  scripts/migration.mjs
  styles/babonus.css
  templates/builder_components/text_text_keys.hbs
  templates/subapplications/keysDialog.hbs
Labels: Enhancement, Breaking

#179 Use roll data to enrich current bonuses' descriptions, and add ability to copy id/uuid of a babonus
  scripts/applications/babonus.mjs
  styles/babonus.css
  templates/babonus.hbs
Labels: UI

#183 Add `healthPercentage` filter, fix unavailable filter section showing added filters, stop `babonus.fromUuid` calling itself
  README.md
  lang/en.json
  scripts/applications/babonus.mjs
  scripts/applications/dataModel.mjs
  scripts/constants.mjs
  scripts/filters.mjs
  scripts/public_api.mjs
  styles/babonus.css
  templates/babonus.hbs
  templates/builder_components/select_range.hbs
Labels: Bug, Feature Request

#184 10.5.0: Ability Checks
  README.md
  lang/en.json
  scripts/applications/appliedBonusesDialog.mjs
  scripts/applications/auraConfigurationApp.mjs
  scripts/applications/babonus.mjs
  scripts/applications/bonusCollector.mjs
  scripts/applications/consumptionApp.mjs
  scripts/applications/dataFields.mjs
  scripts/applications/dataModel.mjs
  scripts/applications/keysDialog.mjs
  scripts/applications/rollConfigApp.mjs
  scripts/constants.mjs
  scripts/filters.mjs
  scripts/helpers/helpers.mjs
  scripts/hooks.mjs
  scripts/migration.mjs
  scripts/public_api.mjs
  setup.mjs
  styles/babonus.css
  templates/babonus.hbs
  templates/builder_components/range_select.hbs
  templates/builder_components/text_text_keys.hbs
  templates/subapplications/appliedBonusesDialog.hbs
  templates/subapplications/auraConfigurationApp.hbs
  templates/subapplications/consumptionApp.hbs
  templates/subapplications/keysDialog.hbs
Labels: Bug, Enhancement, Feature Request, UI

#186 Translations update from Foundry Hub - Weblate
  lang/fr.json
Labels: Localization
