Repository krbz999/babonus, pull requests merged in 2023-06, with the labels that each got.

#224 Translations update from Foundry Hub - Weblate
  lang/fr.json
Labels: Localization

#238 Translations update from Foundry Hub - Weblate
  lang/fr.json
Labels: localization

#237 Allow for creature types filter to evaluate multiple races
  scripts/filters.mjs
Labels: enhancement, filters
