Repository krbz999/babonus, pull requests merged in 2023-02, with the labels that each got.

#110 Translations update from Foundry Hub - Weblate
  lang/fr.json
Labels: Localization

#120 Consume spell slots for optional bonuses
  README.md
  lang/en.json
  scripts/applications/consumptionApp.mjs
  scripts/applications/dataModel.mjs
  scripts/constants.mjs
  scripts/filters.mjs
  scripts/helpers/helpers.mjs
  scripts/helpers/rollConfigHelpers.mjs
  scripts/hooks.mjs
  styles/babonus.css
  templates/subapplications/optionalBonuses.hbs
Labels: Bug, Enhancement

#125 Combine into one application
  lang/en.json
  lang/fr.json
  scripts/applications/auraConfigurationApp.mjs
  scripts/applications/babonus.mjs
  scripts/applications/consumptionApp.mjs
  scripts/applications/dataModel.mjs
  scripts/applications/filterPicker.mjs
  scripts/applications/keysDialog.mjs
  scripts/constants.mjs
  scripts/helpers/filterPickerHelpers.mjs
  scripts/helpers/helpers.mjs
  scripts/helpers/rollConfigHelpers.mjs
  styles/babonus.css
  templates/babonus.hbs
  templates/builder_components/_bonuses.hbs
  templates/builder_components/_current_bonuses.hbs
  templates/builder_components/_required_fields.hbs
  templates/builder_components/checkboxes.hbs
  templates/builder_components/checkboxes_select.hbs
  templates/builder_components/label_checkbox_label_checkbox.hbs
  templates/builder_components/text_dash_text.hbs
  templates/builder_components/text_keys.hbs
  templates/builder_components/text_select_text.hbs
  templates/builder_components/text_text_keys.hbs
  templates/builder_components/textarea.hbs
  templates/subapplications/auraConfigurationApp.hbs
  templates/subapplications/consumptionApp.hbs
  templates/subapplications/filterPicker.hbs
  templates/subapplications/keysDialog.hbs
  templates/subapplications/keysDouble.hbs
  templates/subapplications/keysSingle.hbs
  templates/subapplications/optionalBonuses.hbs
Labels: Bug, Enhancement, UI, Localization

#134 Roll Configuration app, and the optional consumption of effects
  lang/en.json
  scripts/applications/auraConfigurationApp.mjs
  scripts/applications/babonus.mjs
  scripts/applications/consumptionApp.mjs
  scripts/applications/dataModel.mjs
  scripts/applications/keysDialog.mjs
  scripts/applications/rollConfigApp.mjs
  scripts/constants.mjs
  scripts/filters.mjs
  scripts/helpers/bonusCollector.mjs
  scripts/helpers/helpers.mjs
  scripts/helpers/rollConfigHelpers.mjs
  scripts/helpers/templateHelpers.mjs
  scripts/hooks.mjs
  scripts/migration.mjs
  scripts/public_api.mjs
  scripts/setup.mjs
  setup.mjs
  styles/babonus.css
  templates/babonus.hbs
  templates/subapplications/auraConfigurationApp.hbs
  templates/subapplications/consumptionApp.hbs
  templates/subapplications/keysDialog.hbs
  templates/subapplications/optionalBonuses.hbs
Labels: Bug, Enhancement, Feature Request, UI

#137 10.4.0
  README.md
  lang/en.json
  lang/fr.json
  module.json
  scripts/applications/auraConfigurationApp.mjs
  scripts/applications/babonus.mjs
  scripts/applications/bonusCollector.mjs
  scripts/applications/consumptionApp.mjs
  scripts/applications/dataFields.mjs
  scripts/applications/dataModel.mjs
  scripts/applications/filterPicker.mjs
  scripts/applications/keysDialog.mjs
  scripts/applications/rollConfigApp.mjs
  scripts/constants.mjs
  scripts/filters.mjs
  scripts/helpers/bonusCollector.mjs
  scripts/helpers/filterPickerHelpers.mjs
  scripts/helpers/helpers.mjs
  scripts/helpers/rollConfigHelpers.mjs
  scripts/helpers/templateHelpers.mjs
  scripts/hooks.mjs
  scripts/migration.mjs
  scripts/public_api.mjs
  scripts/setup.mjs
  setup.mjs
  styles/babonus.css
  templates/babonus.hbs
  templates/builder_components/_bonuses.hbs
  templates/builder_components/_current_bonuses.hbs
  templates/builder_components/_required_fields.hbs
  templates/builder_components/checkboxes.hbs
  templates/builder_components/checkboxes_select.hbs
  templates/builder_components/label_checkbox_label_checkbox.hbs
  templates/builder_components/text_dash_text.hbs
  templates/builder_components/text_keys.hbs
  templates/builder_components/text_select_text.hbs
  templates/builder_components/text_text_keys.hbs
  templates/builder_components/textarea.hbs
  templates/subapplications/auraConfigurationApp.hbs
  templates/subapplications/consumptionApp.hbs
  templates/subapplications/filterPicker.hbs
  templates/subapplications/keysDialog.hbs
  templates/subapplications/keysDouble.hbs
  templates/subapplications/keysSingle.hbs
  templates/subapplications/optionalBonuses.hbs
Labels: Enhancement

#141 Translations update from Foundry Hub - Weblate
  lang/fr.json
Labels: Localization
