Repository krbz999/babonus, pull requests merged in 2023-10, with the labels that each got.

#295 Translations update from Foundry Hub - Weblate
  lang/fr.json
Labels: localization

#300 Release 11.4.0
  README.md
  lang/en.json
  lang/fr.json
  module.json
  scripts/applications/auraConfigurationApp.mjs
  scripts/applications/babonus-sheet.mjs
  scripts/applications/babonus.mjs
  scripts/applications/bonusCollector.mjs
  scripts/applications/consumptionApp.mjs
  scripts/applications/rollConfigApp.mjs
  scripts/data/AuraModel.mjs
  scripts/data/BabonusModel.mjs
  scripts/data/ConsumptionModel.mjs
  scripts/data/FilterMixin.mjs
  scripts/data/ModifiersModel.mjs
  scripts/data/_module.mjs
  scripts/data/fields/ArbitraryComparisonField.mjs
  scripts/data/fields/CheckboxFields.mjs
  scripts/data/fields/CustomScriptsField.mjs
  scripts/data/fields/FeatureTypesField.mjs
  scripts/data/fields/HealthPercentagesField.mjs
  scripts/data/fields/RemainingSpellSlotsField.mjs
  scripts/data/fields/SemicolonFields.mjs
  scripts/data/fields/SpellComponentsField.mjs
  scripts/data/fields/TokenSizesField.mjs
  scripts/filters.mjs
  scripts/hooks.mjs
  styles/babonus.css
  templates/babonus-sheet.hbs
  templates/babonus.hbs
  templates/parts/bonuses-modifiers.hbs
  templates/parts/checkboxes-select.hbs
  templates/parts/checkboxes.hbs
  templates/parts/double-select.hbs
  templates/parts/range-select.hbs
  templates/parts/select-number-checkbox.hbs
  templates/parts/text-dash-text.hbs
  templates/parts/text-keys.hbs
  templates/parts/text-select-text.hbs
  templates/parts/textarea.hbs
  templates/subapplications/auraConfigurationApp.hbs
  templates/subapplications/consumptionApp.hbs
Labels: bug, enhancement, ui, localization

#305 11.4.1
  lang/fr.json
  module.json
  scripts/applications/babonus-sheet.mjs
  scripts/data/AuraModel.mjs
  scripts/data/BabonusModel.mjs
  scripts/helpers/rollHooks.mjs
Labels: bug, ui, localization

#307 11.4.2
  .github/workflows/main.yml
  README.md
  lang/en.json
  module.json
  scripts/applications/babonus-sheet.mjs
  scripts/applications/rollConfigApp.mjs
  scripts/data/BabonusModel.mjs
  scripts/data/ConsumptionModel.mjs
  styles/babonus.css
  styles/keys.css
  styles/optionals.css
  styles/overview.css
  styles/sheet.css
  styles/workshop.css
  templates/babonus-sheet.hbs
Labels: documentation, enhancement
