Repository krbz999/babonus, pull requests merged in 2024-04, with the labels that each got.

#394 11.10.0
  .eslintrc.json
  .gitignore
  README.md
  lang/en.json
  lang/fr.json
  lang/pt-BR.json
  module.json
  package-lock.json
  package.json
  scripts/api.mjs
  scripts/applications/babonus-sheet.mjs
  scripts/applications/babonus-workshop.mjs
  scripts/applications/bonus-collector.mjs
  scripts/applications/character-sheet-tab.mjs
  scripts/applications/keys-dialog.mjs
  scripts/applications/optional-selector.mjs
  scripts/constants.mjs
  scripts/data/aura-model.mjs
  scripts/data/babonus-model.mjs
  scripts/data/consumption-model.mjs
  scripts/data/fields/checkbox-fields.mjs
  scripts/data/fields/semicolon-fields.mjs
  scripts/data/filter-mixin.mjs
  scripts/data/modifiers-model.mjs
  scripts/filter-manager.mjs
  scripts/helpers/roll-hooks.mjs
  scripts/hooks.mjs
  styles/keys.css
  styles/shared.css
  styles/sheet.css
  templates/babonus-sheet.hbs
  templates/subapplications/character-sheet-tab.hbs
  templates/subapplications/keys-dialog.hbs
Labels: bug, documentation, enhancement, breaking, ui, localization, filters, api

#395 Update pt-BR.json
  lang/pt-BR.json
Labels: localization

#399 11.10.1
  .eslintrc.json
  .gitattributes
  lang/pt-BR.json
  scripts/applications/babonus-sheet.mjs
  scripts/applications/babonus-workshop.mjs
  scripts/applications/character-sheet-tab.mjs
  scripts/applications/optional-selector.mjs
Labels: bug, localization

#405 11.10.3
  .eslintrc.json
  .vscode/settings.json
  README.md
  lang/en.json
  scripts/api.mjs
  scripts/applications/babonus-sheet.mjs
  scripts/applications/babonus-workshop.mjs
  scripts/applications/bonus-collector.mjs
  scripts/applications/character-sheet-tab.mjs
  scripts/data/aura-model.mjs
  scripts/data/babonus-model.mjs
  scripts/data/consumption-model.mjs
  scripts/data/fields/arbitrary-comparison-field.mjs
  scripts/data/fields/checkbox-fields.mjs
  scripts/data/fields/custom-scripts-field.mjs
  scripts/data/fields/feature-types-field.mjs
  scripts/data/fields/health-percentages-field.mjs
  scripts/data/fields/remaining-spell-slots-field.mjs
  scripts/data/fields/semicolon-fields.mjs
  scripts/data/fields/token-sizes-field.mjs
  scripts/data/modifiers-model.mjs
  scripts/filter-manager.mjs
  scripts/helpers/roll-hooks.mjs
  styles/shared.css
  styles/sheet.css
  templates/babonus-sheet.hbs
  templates/subapplications/character-sheet-tab.hbs
Labels: enhancement, api

#406 Update pr-BR lang
  lang/pt-BR.json
Labels: localization
