Repository krbz999/babonus, pull requests merged in 2024-03, with the labels that each got.

#365 11.9
  lang/en.json
  module.json
  scripts/api.mjs
  scripts/applications/applied-bonuses-dialog.mjs
  scripts/applications/babonus-sheet.mjs
  scripts/applications/babonus-workshop.mjs
  scripts/applications/bonus-collector.mjs
  scripts/applications/character-sheet-tab.mjs
  scripts/applications/keys-dialog.mjs
  scripts/applications/optional-selector.mjs
  scripts/data/_module.mjs
  scripts/data/aura-model.mjs
  scripts/data/babonus-model.mjs
  scripts/data/consumption-model.mjs
  scripts/data/fields/checkbox-fields.mjs
  scripts/data/fields/semicolon-fields.mjs
  scripts/data/fields/spell-components-field.mjs
  scripts/data/modifiers-model.mjs
  scripts/filter-manager.mjs
  scripts/helpers/roll-hooks.mjs
  styles/keys.css
  styles/optionals.css
  styles/shared.css
  styles/sheet.css
  templates/babonus-sheet.hbs
  templates/subapplications/character-sheet-tab.hbs
Labels: bug, enhancement, breaking, ui, filters, api

#377 Release 11.9.3
  scripts/applications/babonus-sheet.mjs
  scripts/applications/bonus-collector.mjs
  scripts/helpers/roll-hooks.mjs
  scripts/hooks.mjs
  styles/shared.css
  styles/sheet.css
Labels: bug, enhancement, ui

#381 11.9.4
  lang/en.json
  module.json
  scripts/data/babonus-model.mjs
  scripts/data/fields/semicolon-fields.mjs
  scripts/filter-manager.mjs
  scripts/helpers/roll-hooks.mjs
Labels: enhancement

#386 Translate to pt-BR
  lang/pt-BR.json
  module.json
Labels: localization
